- name: zabbix agent install
  hosts: 
  become: true
  tasks:
    - name: add zabbix agent repo
      yum:
          name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
          state: present
    - name: zabbix-agent install
      yum:
          name: zabbix-agent
          state: present
    - name: zabbix-agent server config
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "Server=127.0.0.1"
        replace: "Server=111.111.111.111"

    - name: zabbix-agent serveractive config
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "ServerActive=127.0.0.1"
        replace: "ServerActive=111.111.111.111"
        
    - name: zabbix-agent service
      service:
        name: zabbix-agent
        state: started



//  - name: Ansible replace multiple words example
      replace:
        path: /Users/mdtutorials2/Documents/Ansible/intext.txt
        regexp: "{{ item }}"
        replace: "dog"
      with_items:
      - 'cat'
      - 'tiger'
      - 'lion'
     
 //  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# HostMetadataItem='
      line: 'HostMetadataItem=system.uname'
      become: true
      
//    - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'
    become: true

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive={{ zabbix_server }}'
    become: true

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname=Zabbix server'
      line: '#Hostname='
    become: true

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# HostMetadata='
      line: 'HostMetadata=Linux'
    become: true

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# HostMetadataItem='
      line: 'HostMetadataItem=system.uname'
    become: true
    
    
    
    // - name: elasticsearch config modify
         lineinfile:
            path: /etc/~~~
            regexp: '{{ item.from }}'
            line: '{{ item.to }}'
         with_items:
          - { from: '#network.host: 192.168.0.1', to: 'network.host:0.0.0.0'}
          - { from: '#http.port:9200', to: 'http.port: 9200'}
      
