- name: ntpconf modify
  hosts: all
  become: true
  tasks:
    - name: config file modify
      replace:
        path: /ansibletest/ntp.conf
        regexp: "sshopen=yes"
        replace: "sshopen=no"
        
  
